# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame)
        self.stackedWidget.setStyleSheet("background-color: rgba(255, 255, 255, 80);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.home)
        self.tableWidget.setGeometry(QtCore.QRect(60, 40, 601, 411))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.home)
        self.cart = QtWidgets.QWidget()
        self.cart.setObjectName("cart")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cart)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.cart)
        self.tableWidget_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"     border-radius:0px;\n"
"}\n"
"QTableWidget:item{\n"
"    border-bottom:1px dotted;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget_2.setTabKeyNavigation(True)
        self.tableWidget_2.setProperty("showDropIndicator", True)
        self.tableWidget_2.setAlternatingRowColors(False)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.cart)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 0, 0);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(100, -1, 50, -1)
        self.horizontalLayout_5.setSpacing(50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.cart)
        font = QtGui.QFont()
        font.setBold(False)
        font.setStrikeOut(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setToolTipDuration(-2)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 0);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 249, 164);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(245, 255, 64);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.cart)
        self.pushButton_4.setToolTipDuration(-2)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 0);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 249, 164);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(245, 255, 64);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.cart)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.profile)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(13, 339, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setToolTipDuration(-2)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setToolTipDuration(-2)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setToolTipDuration(-2)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setToolTipDuration(-2)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setToolTipDuration(-2)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setToolTipDuration(-2)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setToolTipDuration(-2)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setToolTipDuration(-2)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setToolTipDuration(-2)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_4.addWidget(self.pushButton_16)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 255, 0, 150), stop:0.166 rgba(0, 255, 255, 150), stop:0.333 rgba(0, 0, 255, 150), stop:0.5 rgba(255, 0, 255, 150), stop:0.666 rgba(255, 0, 0, 150), stop:0.833 rgba(255, 0, 0, 150), stop:1 rgba(255, 255, 0, 150));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 255, 255), stop:0.166 rgba(255, 0, 255, 255), stop:0.333 rgba(255, 0, 0, 255), stop:0.5 rgba(255, 0, 0, 255), stop:0.666 rgba(255, 255, 0, 255), stop:0.833 rgba(0, 255, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_4.addWidget(self.pushButton_14)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.profile)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setToolTipDuration(-2)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_7.addWidget(self.pushButton_15)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.profile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(20, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("萝莉体 第二版")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setToolTipDuration(-2)
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 18pt \"萝莉体 第二版\";\n"
"border-radius:0px;\n"
"color: rgb(170, 0, 255);")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.textBrowser.setMarkdown("")
        self.textBrowser.setPlaceholderText("")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 15)
        self.horizontalLayout_8.setStretch(2, 4)
        self.horizontalLayout_8.setStretch(3, 14)
        self.horizontalLayout_8.setStretch(4, 4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 17)
        self.verticalLayout_5.setStretch(2, 2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.profile)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(80, 0, 80, 0)
        self.horizontalLayout_2.setSpacing(160)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setToolTipDuration(-2)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(85, 255, 0);\n"
"    border-image:url(imgs/customer/view.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(166, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(12, 255, 69);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setToolTipDuration(-2)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(85, 255, 0);\n"
"    border-image:url(imgs/customer/cart_empty.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(166, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(12, 255, 69);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setToolTipDuration(-2)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(85, 255, 0);\n"
"    border-image:url(imgs/customer/user.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(166, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(12, 255, 69);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 25)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 20)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(Form.turn_to_0) # type: ignore
        self.pushButton_2.clicked.connect(Form.turn_to_1) # type: ignore
        self.pushButton_3.clicked.connect(Form.turn_to_2) # type: ignore
        self.pushButton_4.clicked.connect(Form.buy_all) # type: ignore
        self.pushButton_5.clicked.connect(Form.clear_all) # type: ignore
        self.pushButton_6.clicked.connect(Form.change_nickname) # type: ignore
        self.pushButton_8.clicked.connect(Form.charge) # type: ignore
        self.pushButton_16.clicked.connect(Form.show_start) # type: ignore
        self.pushButton_15.clicked.connect(Form.refresh_text) # type: ignore
        self.pushButton_7.clicked.connect(Form.change_password) # type: ignore
        self.pushButton_9.clicked.connect(Form.check_purchased_items) # type: ignore
        self.pushButton_10.clicked.connect(Form.open_points_mall) # type: ignore
        self.pushButton_11.clicked.connect(Form.user_setting) # type: ignore
        self.pushButton_12.clicked.connect(Form.register_shopkeeper) # type: ignore
        self.pushButton_14.clicked.connect(Form.log_out) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.pushButton_3)
        Form.setTabOrder(self.pushButton_3, self.tableWidget_2)
        Form.setTabOrder(self.tableWidget_2, self.pushButton_4)
        Form.setTabOrder(self.pushButton_4, self.pushButton_5)
        Form.setTabOrder(self.pushButton_5, self.pushButton_6)
        Form.setTabOrder(self.pushButton_6, self.pushButton_7)
        Form.setTabOrder(self.pushButton_7, self.pushButton_8)
        Form.setTabOrder(self.pushButton_8, self.pushButton_9)
        Form.setTabOrder(self.pushButton_9, self.pushButton_10)
        Form.setTabOrder(self.pushButton_10, self.pushButton_11)
        Form.setTabOrder(self.pushButton_11, self.pushButton_16)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "商品名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "价格"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "商家"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "商品简介"))
        self.tableWidget_2.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "商品名"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "单价&数量"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "总价(元)"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "商家"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "类型"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "商品简介"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "添加时间"))
        self.pushButton_5.setToolTip(_translate("Form", "没事了别装b(*￣3￣)╭"))
        self.pushButton_5.setText(_translate("Form", "清空购物车"))
        self.pushButton_4.setToolTip(_translate("Form", "all in all in（￣︶￣）↗　"))
        self.pushButton_4.setText(_translate("Form", "结算所有"))
        self.label_2.setToolTip(_translate("Form", "才不是欢迎你呢(づ￣ 3￣)づ"))
        self.pushButton_6.setToolTip(_translate("Form", "修改昵称"))
        self.pushButton_6.setText(_translate("Form", "修改昵称"))
        self.pushButton_7.setToolTip(_translate("Form", "修改密码"))
        self.pushButton_7.setText(_translate("Form", "修改密码"))
        self.pushButton_8.setToolTip(_translate("Form", "点我充值"))
        self.pushButton_8.setText(_translate("Form", "余额"))
        self.pushButton_9.setToolTip(_translate("Form", "查看购买的物品"))
        self.pushButton_9.setText(_translate("Form", "查看已购买的商品"))
        self.pushButton_10.setToolTip(_translate("Form", "打开积分商城"))
        self.pushButton_10.setText(_translate("Form", "积分商城"))
        self.pushButton_11.setToolTip(_translate("Form", "打开设置"))
        self.pushButton_11.setText(_translate("Form", "设置"))
        self.pushButton_12.setToolTip(_translate("Form", "点我注册成商家"))
        self.pushButton_12.setText(_translate("Form", "成为商家"))
        self.pushButton_16.setToolTip(_translate("Form", "撒哟拉拉＞﹏＜"))
        self.pushButton_16.setText(_translate("Form", "退出登录"))
        self.pushButton_14.setText(_translate("Form", "注销"))
        self.pushButton_15.setToolTip(_translate("Form", "请等待十几秒"))
        self.pushButton_15.setText(_translate("Form", "点我刷新"))
        self.textBrowser.setToolTip(_translate("Form", "我真不是舔狗"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'萝莉体 第二版\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setToolTip(_translate("Form", "主页"))
        self.pushButton_2.setToolTip(_translate("Form", "购物车"))
        self.pushButton_3.setToolTip(_translate("Form", "我的"))
