# Form implementation generated from reading ui file 'shopkeeper.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 150, 161, 330))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.list_items) # type: ignore
        self.pushButton_2.clicked.connect(Form.change_pwd) # type: ignore
        self.pushButton_3.clicked.connect(Form.change_sub_pwd) # type: ignore
        self.pushButton_4.clicked.connect(Form.check_listing_items) # type: ignore
        self.pushButton_5.clicked.connect(Form.check_listed_items) # type: ignore
        self.pushButton_6.clicked.connect(Form.check_delisted_items) # type: ignore
        self.pushButton_7.clicked.connect(Form.show_start) # type: ignore
        self.pushButton_8.clicked.connect(Form.log_out) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "上架商品"))
        self.pushButton_2.setText(_translate("Form", "修改密码"))
        self.label.setText(_translate("Form", "总收入"))
        self.pushButton_3.setText(_translate("Form", "修改上架密码"))
        self.pushButton_4.setText(_translate("Form", "查看正在审核的商品"))
        self.pushButton_5.setText(_translate("Form", "查看已上架的商品"))
        self.pushButton_6.setText(_translate("Form", "查看已下架的商品"))
        self.pushButton_7.setText(_translate("Form", "退出登录"))
        self.pushButton_8.setText(_translate("Form", "注销"))
