# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 401, 301))
        self.stackedWidget.setObjectName("stackedWidget")
        self.start = QtWidgets.QWidget()
        self.start.setObjectName("start")
        self.frame = QtWidgets.QFrame(parent=self.start)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(1, 1, 401, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("#frame{\n"
                                 "    background-color: rgb(12, 235, 255);\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 340, 80))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.label.setToolTipDuration(-5)
        self.label.setStyleSheet("color: rgb(85, 255, 255);\n"
                                 "background-color: rgb(190, 255, 245);\n"
                                 "border-radius:30px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 110, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("border-radius:15px;\n"
                                    "color: rgb(170, 170, 255);")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(15)
        self.lineEdit.setFrame(True)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 180, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_2.setStyleSheet("border-radius:15px;\n"
                                      "color: rgb(170, 170, 255);")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(20)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(60, 250, 75, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "    background-color: rgb(255, 255, 0);\n"
                                      "    border-radius:8px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(255, 255, 153);\n"
                                      "}\n"
                                      "QPushButton:pressed{\n"
                                      "    background-color: rgb(218, 255, 55);\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 250, 75, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "    background-color: rgb(255, 255, 0);\n"
                                        "    border-radius:8px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(255, 255, 153);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(218, 255, 55);\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBox.setGeometry(QtCore.QRect(290, 255, 79, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 225, 79, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.stackedWidget.addWidget(self.start)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setObjectName("register_page")
        self.frame_2 = QtWidgets.QFrame(parent=self.register_page)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.frame_2.setStyleSheet("#frame_2{\n"
                                   "    background-color: rgb(255, 170, 255);\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 55, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("border-radius:15px;\n"
                                      "color: rgb(170, 170, 255);")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(12)
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setCursorPosition(0)
        self.lineEdit_3.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 135, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("border-radius:15px;\n"
                                      "color: rgb(170, 170, 255);")
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setMaxLength(20)
        self.lineEdit_4.setFrame(True)
        self.lineEdit_4.setCursorPosition(0)
        self.lineEdit_4.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 215, 320, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("border-radius:15px;\n"
                                      "color: rgb(170, 170, 255);")
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setMaxLength(20)
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setCursorPosition(0)
        self.lineEdit_5.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 260, 75, 30))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.pushButton_3.setStyleSheet("border-radius:0px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 351, 18))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 265, 150, 18))
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 185, 90, 18))
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 105, 211, 18))
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(230, 190, 120, 18))
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 16, 16))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ClosedHandCursor))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 170, 255);\n"
                                        "border-radius:0px;\n"
                                        "")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.register_page)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(Form.login)  # type: ignore
        self.pushButton_2.clicked.connect(Form.open_register_page)  # type: ignore
        self.pushButton_3.clicked.connect(Form.register)  # type: ignore
        self.pushButton_4.clicked.connect(Form.back_to_start)  # type: ignore
        self.lineEdit_3.editingFinished.connect(Form.check_username)  # type: ignore
        self.lineEdit_4.editingFinished.connect(Form.verify_pwd_strength)  # type: ignore
        self.lineEdit_5.editingFinished.connect(Form.pwd_check)  # type: ignore
        self.checkBox_2.clicked.connect(Form.show_pwd)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.lineEdit_2)
        Form.setTabOrder(self.lineEdit_2, self.pushButton)
        Form.setTabOrder(self.pushButton, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.checkBox)
        Form.setTabOrder(self.checkBox, self.pushButton_4)
        Form.setTabOrder(self.pushButton_4, self.lineEdit_3)
        Form.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Form.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Form.setTabOrder(self.lineEdit_5, self.pushButton_3)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setToolTip(_translate("Form", "华生你发现了盲点"))
        self.label.setText(_translate("Form", "一 雪 商 城"))
        self.lineEdit.setToolTip(_translate("Form", "请输入您的账号"))
        self.lineEdit.setPlaceholderText(_translate("Form", " 账号："))
        self.lineEdit_2.setToolTip(_translate("Form", "请输入您的密码"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", " 密码："))
        self.pushButton.setText(_translate("Form", "登录"))
        self.pushButton_2.setText(_translate("Form", "注册"))
        self.checkBox.setText(_translate("Form", "我是商家"))
        self.checkBox_2.setText(_translate("Form", "显示密码"))
        self.lineEdit_3.setToolTip(_translate("Form", "请输入您的账号"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", " 账号："))
        self.lineEdit_4.setToolTip(_translate("Form", "请输入您的账号"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", " 密码："))
        self.lineEdit_5.setToolTip(_translate("Form", "请输入您的账号"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", " 确定密码："))
        self.pushButton_3.setText(_translate("Form", "点我注册"))
        self.label_2.setText(_translate("Form", "请以字母开头+数字组成亲，密码设置的请不要过于简单的(⊙x⊙;)"))
        self.label_6.setText(_translate("Form", "大小写字母+数字组合"))
        self.pushButton_4.setText(_translate("Form", "←"))
